### ISSUE TITLE
release里没有东西可以下载啊

### ISSUE THREAD

**Issue by Destiny713** [polichan/SportCampus#2]
There aren’t any releases here
Releases are powered by tagging specific points of history in a repository. They’re great for marking release points like v1.0.

**Comment by polichan** [comment]
Thanks for your notice. I will release it ASAP. For now you can clone this repo and run it from IDE like Pycharm.

**Comment by polichan** [comment]
We have released the v1.0, please check it out in release page. Also, the issue is going to be closed.
