### ISSUE TITLE
10月11日出错,好像是接口改了

### ISSUE THREAD

**Issue by FallenSky-1** [polichan/SportCampus#3]
显示:请更新APP至最新版本

**Comment by polichan** [comment]
这个问题的话，你可以自己抓下包，改一下请求头的版本号，应该就不会显示这个提示了。如果你愿意等的话，等我这段时间有空了我会重写整个核心 @FallenSky-1

**Comment by Zxilly** [comment]
实际上，你把那个http接口地址改成https就行了。。。

**Comment by polichan** [comment]
> 实际上，你把那个http接口地址改成https就行了。。。

针对这个问题，如果你愿意，欢迎提交PR。

PS. 关于重写：这个脚本核心代码是另一个作者写的，写得比较狂野。打算之后抽时间自己造一个。

**Comment by Zxilly** [comment]
> > 实际上，你把那个http接口地址改成https就行了。。。
> 
> 针对这个问题，如果你愿意，欢迎提交PR。
> 
> PS. 关于重写：这个脚本核心代码是另一个作者写的，写得比较狂野。打算之后抽时间自己造一个。

我的fork分支做了一些本地化修改，我不知道怎么抽出若干个commit来生成PR
